[tool.poetry]
name = "yuheng-plugin-registry"
version = "1.0.0"
description = ""
authors = ["快乐的老鼠宝宝 <laoshubaby@protonmail.com>"]
license = "CC-0"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.6"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
